imports:
    - php

filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
        - 'tools/*'
        - '*.min.js'
        - '*/vendor/*'
        - 'build/*'
        - 'src/kernel.php'
    dependency_paths:
        - 'tools/*'
build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.1
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -
                # command: "composer phpunit"
                command: "XDEBUG_MODE=coverage vendor/bin/phpunit src"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"

checks:
    php: true
    javascript: true
coding_style:
    php:
        spaces:
            around_operators:
                bitwise: false
            other:
                after_type_cast: false